from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from databases import Database

# Define your database connection string

app = FastAPI()
# database = Database(DATABASE_URL)

# class Student(BaseModel):
#     studentId: int = None  # Will be automatically generated by the database
#     studentName: str

# @app.on_event("startup")
# async def startup():
#     await database.connect()

# @app.on_event("shutdown")
# async def shutdown():
#     await database.disconnect()

# @app.post("/students/")
# async def create_student(student: Student):
#     query = "INSERT INTO students (student_name) VALUES (:student_name) RETURNING student_id"
#     student_id = await database.execute(query=query, values={"student_name": student.studentName})
#     return {"student_id": student_id, "student_name": student.studentName}

@app.get("/")
async def read_students():
    # query = "SELECT * FROM students"
    return {"Hello","World"}
